install.packages("WRS2")
library(WRS2)
install.packages("remotes")
remotes::install_github("GRousselet/bootcorci")
library(bootcorci)
Data <- read.csv("/Users/nataliabulgakova/Documents/data/Miguel/Figure 5/Fig7distal.csv")
x1 <-c(na.omit(Data[,1]))
y1 <-c(na.omit(Data[,2]))
x2 <-c(na.omit(Data[,3]))
y2 <-c(na.omit(Data[,4]))

res <- twocorci(x1, y1, x2, y2, method = "pearson", alternative = "two.sided")
res1 <- corci(x1, y1, method = "pearson", saveboot = FALSE)
res2 <- corci(x2, y2, method = "pearson", saveboot = FALSE)
